name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Baixar o código do repositório
      - uses: actions/checkout@v2

      # Fazer o deploy no Heroku
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_FRONT }}
          heroku_app_name: "teixeira-task-manager" # Nome único no Heroku
          heroku_email: "keuvyntdev@gmail.com"
          appdir: "./fsc-taskmanager-backend"
