name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Baixar o código do repositório
      - uses: actions/checkout@v2

      # Configurar o diretório do frontend
      - name: Navegar para o diretório do frontend
        working-directory: ./fsc-taskmanager-frontend
        run: echo "Entrando no diretório do frontend"

      # Fazer o deploy no Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "teixeira-taskmanager-frontend" # Nome único no Heroku
          heroku_email: "keuvyntdev@gmail.com"
